{% set name = "mystic" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mystic-{{ version }}.tar.gz
  sha256: 619e32b7040a50b59c8d261897ce9fc3a8f9b178020007acb94a30b5bf317393

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - cython >=0.29.30
    - pip
    - python >=3.7
    - setuptools >=42
  run:
    - dill >=0.3.7
    - klepto >=0.2.4
    - mpmath >=0.19
    - numpy >=1.0
    - pathos >=0.3.1
    - pyina >=0.2.8
    - python >=3.7
    - scipy >=0.6.0
    - sympy >=0.6.7

test:
  imports:
    - mystic
  commands:
    - pip check
  requires:
    - pip

about:
  home: mystic.rtfd.io
  dev_url: https://github.com/uqfoundation/mystic
  summary: Highly-constrained non-convex optimization and uncertainty quantification
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
