{% set name = "mystic" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mystic-{{ version }}.tar.gz
  sha256: 5a35d0839e04014161c6b24f310dab6e12649a99976b07aa282c2f06799a5b7f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - cython >=0.29.30
    - pip
    - python >=3.7
    - setuptools >=42
  run:
    - dill >=0.3.9
    - klepto >=0.2.6
    - mpmath >=0.19
    - numpy >=1.0
    - pathos >=0.3.1
    - pyina >=0.2.8
    - python >=3.7
    - scipy >=0.6.0
    - sympy >=0.6.7

test:
  imports:
    - mystic
  commands:
    - pip check
  requires:
    - pip

about:
  home: mystic.rtfd.io
  dev_url: https://github.com/uqfoundation/mystic
  summary: Highly-constrained non-convex optimization and uncertainty quantification
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
