schema_version: 1

context:
  name: mystic
  version: "0.4.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mystic-${{ version }}.tar.gz
  sha256: 94aa49173113bf55e33463afa0cbc9addf5565dc1cc50568e396d3d1ad80d977

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - cython >=0.29.30
    - pip
    - python ${{ python_min }}.*
    - setuptools >=42
  run:
    - dill >=0.4.0
    - klepto >=0.2.7
    - mpmath >=0.19
    - numpy >=1.0
    - pathos >=0.3.4
    - pyina >=0.3.0
    - python >=${{ python_min }}
    - sympy >=0.6.7

tests:
  - python:
      imports:
        - mystic
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Highly-constrained non-convex optimization and uncertainty quantification
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://mystic.rtfd.io
  repository: https://github.com/uqfoundation/mystic

extra:
  recipe-maintainers:
    - thewchan
